# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HappyRapidCart' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'AlamofireImage'
  # Add additional dependencies
  pod 'Parse'

  # Pods for HappyRapidCart

  target 'HappyRapidCartTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HappyRapidCartUITests' do
    # Pods for testing
  end

end
